<?php

require_once __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

echo "=== CREATING COMPREHENSIVE MACHINERY ENTRIES ===\n";

// Get available data for relationships
$sites = DB::table('projects')->select('id', 'workspace')->get();
$categories = DB::table('machinery_categories')->get();
$suppliers = DB::table('suppliers')->get();

echo "Available sites: " . $sites->count() . PHP_EOL;
echo "Available categories: " . $categories->count() . PHP_EOL;
echo "Available suppliers: " . $suppliers->count() . PHP_EOL;

// Fallback data if relationships don't exist
if ($sites->isEmpty()) {
    echo "Warning: No sites found, using fallback data\n";
    $sites = collect([
        (object)['id' => 1, 'workspace' => 1],
        (object)['id' => 2, 'workspace' => 1],
        (object)['id' => 3, 'workspace' => 1],
    ]);
}

if ($categories->isEmpty()) {
    echo "Warning: No categories found, using fallback data\n";
    $categories = collect([
        (object)['id' => 1, 'name' => 'Excavator'],
        (object)['id' => 2, 'name' => 'Crane'],
        (object)['id' => 3, 'name' => 'Bulldozer'],
        (object)['id' => 4, 'name' => 'Loader'],
    ]);
}

if ($suppliers->isEmpty()) {
    echo "Warning: No suppliers found, using fallback data\n";
    $suppliers = collect([
        (object)['id' => 1, 'name' => 'Supplier A'],
        (object)['id' => 2, 'name' => 'Supplier B'],
        (object)['id' => 3, 'name' => 'Supplier C'],
    ]);
}

// Clear existing machinery for clean insertion
echo "\nClearing existing machinery records...\n";
DB::statement('SET FOREIGN_KEY_CHECKS=0;');
DB::table('machineries')->truncate();
DB::statement('SET FOREIGN_KEY_CHECKS=1;');

// Comprehensive machinery data
$machineryData = [
    // Owned Machinery (10 entries)
    [
        'name' => 'JCB Excavator JS200',
        'category_id' => 1,
        'model_number' => 'JS200-2023',
        'manufacturer' => 'JCB',
        'vehicle_number' => 'MH12AB1234',
        'owned_by' => 'owned',
        'operational_status' => 'active',
        'site_id' => 1,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Heavy duty excavator for earthmoving operations',
        'remarks' => 'Well maintained, regularly serviced',
        'capacity' => '20 tons',
        'purchase_date' => '2023-01-15',
        'purchase_value' => 2500000.00,
        'insurance_due_date' => '2025-12-31',
        'puc_due_date' => '2025-06-30',
        'fitness_due_date' => '2025-09-30',
        'last_service_date' => '2024-11-15',
        'maintenance_schedule' => '2025-02-15',
        'rate_type' => null,
        'rate' => null,
        'minimum_billing_hours' => null,
        'diesel_by_company' => null,
        'operator_by_supplier' => null,
        'number_of_operators' => null,
        'supplier_id' => null,
        'rental_agreement_file' => null,
        'ownership_documents_file' => 'jcb_js200_docs.pdf',
    ],
    [
        'name' => 'Tata Hitachi Excavator ZAXIS 210',
        'category_id' => 1,
        'model_number' => 'ZAXIS210-2022',
        'manufacturer' => 'Tata Hitachi',
        'vehicle_number' => 'MH13CD5678',
        'owned_by' => 'owned',
        'operational_status' => 'active',
        'site_id' => 2,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Medium excavator for construction sites',
        'remarks' => 'Excellent fuel efficiency',
        'capacity' => '21 tons',
        'purchase_date' => '2022-03-20',
        'purchase_value' => 3200000.00,
        'insurance_due_date' => '2025-11-30',
        'puc_due_date' => '2025-05-31',
        'fitness_due_date' => '2025-08-31',
        'last_service_date' => '2024-10-20',
        'maintenance_schedule' => '2025-01-20',
        'rate_type' => null,
        'rate' => null,
        'minimum_billing_hours' => null,
        'diesel_by_company' => null,
        'operator_by_supplier' => null,
        'number_of_operators' => null,
        'supplier_id' => null,
        'rental_agreement_file' => null,
        'ownership_documents_file' => 'tata_zaxis_docs.pdf',
    ],
    [
        'name' => 'ACE Crane ACX550',
        'category_id' => 2,
        'model_number' => 'ACX550-2023',
        'manufacturer' => 'ACE',
        'vehicle_number' => 'MH14EF9012',
        'owned_by' => 'owned',
        'operational_status' => 'active',
        'site_id' => 3,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => '55-ton capacity crane for lifting operations',
        'remarks' => 'Certified for heavy lifting',
        'capacity' => '55 tons',
        'purchase_date' => '2023-06-10',
        'purchase_value' => 4500000.00,
        'insurance_due_date' => '2026-01-31',
        'puc_due_date' => '2025-07-31',
        'fitness_due_date' => '2025-10-31',
        'last_service_date' => '2024-12-10',
        'maintenance_schedule' => '2025-03-10',
        'rate_type' => null,
        'rate' => null,
        'minimum_billing_hours' => null,
        'diesel_by_company' => null,
        'operator_by_supplier' => null,
        'number_of_operators' => null,
        'supplier_id' => null,
        'rental_agreement_file' => null,
        'ownership_documents_file' => 'ace_crane_docs.pdf',
    ],
    [
        'name' => 'Komatsu Bulldozer D85EX',
        'category_id' => 3,
        'model_number' => 'D85EX-2022',
        'manufacturer' => 'Komatsu',
        'vehicle_number' => 'MH15GH3456',
        'owned_by' => 'owned',
        'operational_status' => 'active',
        'site_id' => 1,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Heavy bulldozer for land clearing',
        'remarks' => 'Powerful engine, excellent traction',
        'capacity' => '30 tons',
        'purchase_date' => '2022-09-15',
        'purchase_value' => 3800000.00,
        'insurance_due_date' => '2025-10-15',
        'puc_due_date' => '2025-04-15',
        'fitness_due_date' => '2025-07-15',
        'last_service_date' => '2024-11-15',
        'maintenance_schedule' => '2025-02-15',
        'rate_type' => null,
        'rate' => null,
        'minimum_billing_hours' => null,
        'diesel_by_company' => null,
        'operator_by_supplier' => null,
        'number_of_operators' => null,
        'supplier_id' => null,
        'rental_agreement_file' => null,
        'ownership_documents_file' => 'komatsu_dozer_docs.pdf',
    ],
    [
        'name' => 'Voltas Wheel Loader VL1100',
        'category_id' => 4,
        'model_number' => 'VL1100-2023',
        'manufacturer' => 'Voltas',
        'vehicle_number' => 'MH16IJ7890',
        'owned_by' => 'owned',
        'operational_status' => 'breakdown',
        'site_id' => 2,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Wheel loader for material handling',
        'remarks' => 'Under maintenance - hydraulic issue',
        'capacity' => '11 tons',
        'purchase_date' => '2023-04-25',
        'purchase_value' => 1800000.00,
        'insurance_due_date' => '2025-09-25',
        'puc_due_date' => '2025-03-25',
        'fitness_due_date' => '2025-06-25',
        'last_service_date' => '2024-09-25',
        'maintenance_schedule' => '2024-12-25',
        'rate_type' => null,
        'rate' => null,
        'minimum_billing_hours' => null,
        'diesel_by_company' => null,
        'operator_by_supplier' => null,
        'number_of_operators' => null,
        'supplier_id' => null,
        'rental_agreement_file' => null,
        'ownership_documents_file' => 'voltas_loader_docs.pdf',
    ],
    [
        'name' => 'Hyundai Crawler Excavator R210W',
        'category_id' => 1,
        'model_number' => 'R210W-2023',
        'manufacturer' => 'Hyundai',
        'vehicle_number' => 'MH17KL2345',
        'owned_by' => 'owned',
        'operational_status' => 'active',
        'site_id' => 3,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Wheeled excavator for urban construction',
        'remarks' => 'Good mobility, high productivity',
        'capacity' => '21 tons',
        'purchase_date' => '2023-07-30',
        'purchase_value' => 2900000.00,
        'insurance_due_date' => '2026-02-28',
        'puc_due_date' => '2025-08-31',
        'fitness_due_date' => '2025-11-30',
        'last_service_date' => '2024-12-30',
        'maintenance_schedule' => '2025-03-30',
        'rate_type' => null,
        'rate' => null,
        'minimum_billing_hours' => null,
        'diesel_by_company' => null,
        'operator_by_supplier' => null,
        'number_of_operators' => null,
        'supplier_id' => null,
        'rental_agreement_file' => null,
        'ownership_documents_file' => 'hyundai_excavator_docs.pdf',
    ],
    [
        'name' => 'Liebherr Crane LTM 1050-3.1',
        'category_id' => 2,
        'model_number' => 'LTM1050-2022',
        'manufacturer' => 'Liebherr',
        'vehicle_number' => 'MH18MN6789',
        'owned_by' => 'owned',
        'operational_status' => 'active',
        'site_id' => 1,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => '50-ton mobile crane',
        'remarks' => 'All-terrain capability',
        'capacity' => '50 tons',
        'purchase_date' => '2022-11-20',
        'purchase_value' => 5200000.00,
        'insurance_due_date' => '2025-12-20',
        'puc_due_date' => '2025-06-20',
        'fitness_due_date' => '2025-09-20',
        'last_service_date' => '2024-11-20',
        'maintenance_schedule' => '2025-02-20',
        'rate_type' => null,
        'rate' => null,
        'minimum_billing_hours' => null,
        'diesel_by_company' => null,
        'operator_by_supplier' => null,
        'number_of_operators' => null,
        'supplier_id' => null,
        'rental_agreement_file' => null,
        'ownership_documents_file' => 'liebherr_crane_docs.pdf',
    ],
    [
        'name' => 'Kirloskar Water Pump KTP-200',
        'category_id' => 5,
        'model_number' => 'KTP200-2023',
        'manufacturer' => 'Kirloskar',
        'vehicle_number' => 'MH19OP0123',
        'owned_by' => 'owned',
        'operational_status' => 'active',
        'site_id' => 2,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'High capacity water pump for dewatering',
        'remarks' => 'Reliable performance, low maintenance',
        'capacity' => '200 HP',
        'purchase_date' => '2023-05-15',
        'purchase_value' => 450000.00,
        'insurance_due_date' => '2025-08-15',
        'puc_due_date' => '2025-02-15',
        'fitness_due_date' => '2025-05-15',
        'last_service_date' => '2024-10-15',
        'maintenance_schedule' => '2025-01-15',
        'rate_type' => null,
        'rate' => null,
        'minimum_billing_hours' => null,
        'diesel_by_company' => null,
        'operator_by_supplier' => null,
        'number_of_operators' => null,
        'supplier_id' => null,
        'rental_agreement_file' => null,
        'ownership_documents_file' => 'kirloskar_pump_docs.pdf',
    ],
    [
        'name' => 'JCB Backhoe Loader 3DX',
        'category_id' => 6,
        'model_number' => '3DX-2023',
        'manufacturer' => 'JCB',
        'vehicle_number' => 'MH20QR4567',
        'owned_by' => 'owned',
        'operational_status' => 'active',
        'site_id' => 3,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Versatile backhoe loader',
        'remarks' => 'Multi-purpose equipment',
        'capacity' => '3 tons',
        'purchase_date' => '2023-08-10',
        'purchase_value' => 1200000.00,
        'insurance_due_date' => '2026-03-10',
        'puc_due_date' => '2025-09-10',
        'fitness_due_date' => '2025-12-10',
        'last_service_date' => '2024-11-10',
        'maintenance_schedule' => '2025-02-10',
        'rate_type' => null,
        'rate' => null,
        'minimum_billing_hours' => null,
        'diesel_by_company' => null,
        'operator_by_supplier' => null,
        'number_of_operators' => null,
        'supplier_id' => null,
        'rental_agreement_file' => null,
        'ownership_documents_file' => 'jcb_backhoe_docs.pdf',
    ],
    [
        'name' => 'Tata Motor Grader GD553',
        'category_id' => 7,
        'model_number' => 'GD553-2022',
        'manufacturer' => 'Tata',
        'vehicle_number' => 'MH21ST8901',
        'owned_by' => 'owned',
        'operational_status' => 'scrap',
        'site_id' => 1,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Motor grader for road construction',
        'remarks' => 'End of life, to be disposed',
        'capacity' => '15 tons',
        'purchase_date' => '2022-01-30',
        'purchase_value' => 2800000.00,
        'insurance_due_date' => '2024-07-30',
        'puc_due_date' => '2024-01-30',
        'fitness_due_date' => '2024-04-30',
        'last_service_date' => '2023-07-30',
        'maintenance_schedule' => '2023-10-30',
        'rate_type' => null,
        'rate' => null,
        'minimum_billing_hours' => null,
        'diesel_by_company' => null,
        'operator_by_supplier' => null,
        'number_of_operators' => null,
        'supplier_id' => null,
        'rental_agreement_file' => null,
        'ownership_documents_file' => 'tata_grader_docs.pdf',
    ],
    
    // Rental Machinery (12 entries)
    [
        'name' => 'Rental Excavator CAT 320D',
        'category_id' => 1,
        'model_number' => 'CAT320D-2023',
        'manufacturer' => 'Caterpillar',
        'vehicle_number' => 'RT01UV2345',
        'owned_by' => 'rental',
        'operational_status' => 'active',
        'site_id' => 1,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Rental excavator from external supplier',
        'remarks' => 'On monthly rental contract',
        'capacity' => '20 tons',
        'rate_type' => 'hourly',
        'rate' => 1500.00,
        'minimum_billing_hours' => 8,
        'diesel_by_company' => true,
        'operator_by_supplier' => false,
        'number_of_operators' => 1,
        'supplier_id' => 1,
        'rental_agreement_file' => 'cat320d_agreement.pdf',
        'purchase_date' => null,
        'purchase_value' => null,
        'insurance_due_date' => null,
        'puc_due_date' => null,
        'fitness_due_date' => null,
        'last_service_date' => null,
        'maintenance_schedule' => null,
        'ownership_documents_file' => null,
    ],
    [
        'name' => 'Rental Crane Liebherr LTM 1040',
        'category_id' => 2,
        'model_number' => 'LTM1040-2023',
        'manufacturer' => 'Liebherr',
        'vehicle_number' => 'RT02WX6789',
        'owned_by' => 'rental',
        'operational_status' => 'active',
        'site_id' => 2,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Rental crane for specialized lifting',
        'remarks' => 'Daily rental basis',
        'capacity' => '40 tons',
        'rate_type' => 'daily',
        'rate' => 12000.00,
        'minimum_billing_hours' => 8,
        'diesel_by_company' => false,
        'operator_by_supplier' => true,
        'number_of_operators' => 2,
        'supplier_id' => 2,
        'rental_agreement_file' => 'liebherr1040_agreement.pdf',
        'purchase_date' => null,
        'purchase_value' => null,
        'insurance_due_date' => null,
        'puc_due_date' => null,
        'fitness_due_date' => null,
        'last_service_date' => null,
        'maintenance_schedule' => null,
        'ownership_documents_file' => null,
    ],
    [
        'name' => 'Rental Bulldozer Komatsu D65PX',
        'category_id' => 3,
        'model_number' => 'D65PX-2023',
        'manufacturer' => 'Komatsu',
        'vehicle_number' => 'RT03YZ0123',
        'owned_by' => 'rental',
        'operational_status' => 'active',
        'site_id' => 3,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Rental bulldozer for earthmoving',
        'remarks' => 'Monthly rental with operator',
        'capacity' => '25 tons',
        'rate_type' => 'monthly',
        'rate' => 150000.00,
        'minimum_billing_hours' => 160,
        'diesel_by_company' => true,
        'operator_by_supplier' => true,
        'number_of_operators' => 1,
        'supplier_id' => 3,
        'rental_agreement_file' => 'komatsu_d65px_agreement.pdf',
        'purchase_date' => null,
        'purchase_value' => null,
        'insurance_due_date' => null,
        'puc_due_date' => null,
        'fitness_due_date' => null,
        'last_service_date' => null,
        'maintenance_schedule' => null,
        'ownership_documents_file' => null,
    ],
    [
        'name' => 'Rental Loader Volvo L120H',
        'category_id' => 4,
        'model_number' => 'L120H-2023',
        'manufacturer' => 'Volvo',
        'vehicle_number' => 'RT04AB4567',
        'owned_by' => 'rental',
        'operational_status' => 'active',
        'site_id' => 1,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Rental wheel loader',
        'remarks' => 'Hourly rental rate',
        'capacity' => '20 tons',
        'rate_type' => 'hourly',
        'rate' => 1200.00,
        'minimum_billing_hours' => 4,
        'diesel_by_company' => true,
        'operator_by_supplier' => false,
        'number_of_operators' => 1,
        'supplier_id' => 1,
        'rental_agreement_file' => 'volvo_l120h_agreement.pdf',
        'purchase_date' => null,
        'purchase_value' => null,
        'insurance_due_date' => null,
        'puc_due_date' => null,
        'fitness_due_date' => null,
        'last_service_date' => null,
        'maintenance_schedule' => null,
        'ownership_documents_file' => null,
    ],
    [
        'name' => 'Rental Excavator Hitachi ZX200',
        'category_id' => 1,
        'model_number' => 'ZX200-2023',
        'manufacturer' => 'Hitachi',
        'vehicle_number' => 'RT05CD8901',
        'owned_by' => 'rental',
        'operational_status' => 'breakdown',
        'site_id' => 2,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Rental excavator under repair',
        'remarks' => 'Engine issue - supplier handling',
        'capacity' => '20 tons',
        'rate_type' => 'daily',
        'rate' => 8000.00,
        'minimum_billing_hours' => 8,
        'diesel_by_company' => false,
        'operator_by_supplier' => true,
        'number_of_operators' => 1,
        'supplier_id' => 2,
        'rental_agreement_file' => 'hitachi_zx200_agreement.pdf',
        'purchase_date' => null,
        'purchase_value' => null,
        'insurance_due_date' => null,
        'puc_due_date' => null,
        'fitness_due_date' => null,
        'last_service_date' => null,
        'maintenance_schedule' => null,
        'ownership_documents_file' => null,
    ],
    [
        'name' => 'Rental Crane Grove GMK3050',
        'category_id' => 2,
        'model_number' => 'GMK3050-2023',
        'manufacturer' => 'Grove',
        'vehicle_number' => 'RT06EF2345',
        'owned_by' => 'rental',
        'operational_status' => 'active',
        'site_id' => 3,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Rental mobile crane',
        'remarks' => 'Specialized lifting operations',
        'capacity' => '50 tons',
        'rate_type' => 'hourly',
        'rate' => 2500.00,
        'minimum_billing_hours' => 8,
        'diesel_by_company' => true,
        'operator_by_supplier' => true,
        'number_of_operators' => 2,
        'supplier_id' => 3,
        'rental_agreement_file' => 'grove_gmk3050_agreement.pdf',
        'purchase_date' => null,
        'purchase_value' => null,
        'insurance_due_date' => null,
        'puc_due_date' => null,
        'fitness_due_date' => null,
        'last_service_date' => null,
        'maintenance_schedule' => null,
        'ownership_documents_file' => null,
    ],
    [
        'name' => 'Rental Compactor Bomag BW213D',
        'category_id' => 8,
        'model_number' => 'BW213D-2023',
        'manufacturer' => 'Bomag',
        'vehicle_number' => 'RT07GH6789',
        'owned_by' => 'rental',
        'operational_status' => 'active',
        'site_id' => 1,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Rental soil compactor',
        'remarks' => 'Road construction project',
        'capacity' => '10 tons',
        'rate_type' => 'daily',
        'rate' => 6000.00,
        'minimum_billing_hours' => 8,
        'diesel_by_company' => true,
        'operator_by_supplier' => false,
        'number_of_operators' => 1,
        'supplier_id' => 1,
        'rental_agreement_file' => 'bomag_bw213d_agreement.pdf',
        'purchase_date' => null,
        'purchase_value' => null,
        'insurance_due_date' => null,
        'puc_due_date' => null,
        'fitness_due_date' => null,
        'last_service_date' => null,
        'maintenance_schedule' => null,
        'ownership_documents_file' => null,
    ],
    [
        'name' => 'Rental Truck Ashok Leyland 2518',
        'category_id' => 9,
        'model_number' => '2518-2023',
        'manufacturer' => 'Ashok Leyland',
        'vehicle_number' => 'RT08IJ0123',
        'owned_by' => 'rental',
        'operational_status' => 'active',
        'site_id' => 2,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Rental dump truck',
        'remarks' => 'Material transportation',
        'capacity' => '25 tons',
        'rate_type' => 'hourly',
        'rate' => 800.00,
        'minimum_billing_hours' => 8,
        'diesel_by_company' => false,
        'operator_by_supplier' => false,
        'number_of_operators' => 1,
        'supplier_id' => 2,
        'rental_agreement_file' => 'ashok_2518_agreement.pdf',
        'purchase_date' => null,
        'purchase_value' => null,
        'insurance_due_date' => null,
        'puc_due_date' => null,
        'fitness_due_date' => null,
        'last_service_date' => null,
        'maintenance_schedule' => null,
        'ownership_documents_file' => null,
    ],
    [
        'name' => 'Rental Generator Cummins 500kVA',
        'category_id' => 10,
        'model_number' => 'C500D-2023',
        'manufacturer' => 'Cummins',
        'vehicle_number' => 'RT09KL4567',
        'owned_by' => 'rental',
        'operational_status' => 'active',
        'site_id' => 3,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Rental power generator',
        'remarks' => 'Site power supply',
        'capacity' => '500 kVA',
        'rate_type' => 'monthly',
        'rate' => 80000.00,
        'minimum_billing_hours' => 720,
        'diesel_by_company' => true,
        'operator_by_supplier' => false,
        'number_of_operators' => 1,
        'supplier_id' => 3,
        'rental_agreement_file' => 'cummins_500kva_agreement.pdf',
        'purchase_date' => null,
        'purchase_value' => null,
        'insurance_due_date' => null,
        'puc_due_date' => null,
        'fitness_due_date' => null,
        'last_service_date' => null,
        'maintenance_schedule' => null,
        'ownership_documents_file' => null,
    ],
    [
        'name' => 'Rental Mixer Transit Concrete',
        'category_id' => 11,
        'model_number' => 'TCM300-2023',
        'manufacturer' => 'Transit',
        'vehicle_number' => 'RT10MN8901',
        'owned_by' => 'rental',
        'operational_status' => 'active',
        'site_id' => 1,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Rental concrete mixer',
        'remarks' => 'Concrete mixing operations',
        'capacity' => '6 cubic meters',
        'rate_type' => 'hourly',
        'rate' => 1000.00,
        'minimum_billing_hours' => 4,
        'diesel_by_company' => true,
        'operator_by_supplier' => false,
        'number_of_operators' => 2,
        'supplier_id' => 1,
        'rental_agreement_file' => 'transit_mixer_agreement.pdf',
        'purchase_date' => null,
        'purchase_value' => null,
        'insurance_due_date' => null,
        'puc_due_date' => null,
        'fitness_due_date' => null,
        'last_service_date' => null,
        'maintenance_schedule' => null,
        'ownership_documents_file' => null,
    ],
    [
        'name' => 'Rental Roller Hamm HD13',
        'category_id' => 12,
        'model_number' => 'HD13-2023',
        'manufacturer' => 'Hamm',
        'vehicle_number' => 'RT11OP2345',
        'owned_by' => 'rental',
        'operational_status' => 'active',
        'site_id' => 2,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Rental road roller',
        'remarks' => 'Asphalt compaction',
        'capacity' => '13 tons',
        'rate_type' => 'daily',
        'rate' => 7000.00,
        'minimum_billing_hours' => 8,
        'diesel_by_company' => true,
        'operator_by_supplier' => false,
        'number_of_operators' => 1,
        'supplier_id' => 2,
        'rental_agreement_file' => 'hamm_hd13_agreement.pdf',
        'purchase_date' => null,
        'purchase_value' => null,
        'insurance_due_date' => null,
        'puc_due_date' => null,
        'fitness_due_date' => null,
        'last_service_date' => null,
        'maintenance_schedule' => null,
        'ownership_documents_file' => null,
    ],
    [
        'name' => 'Rental Tower Potain MCT205',
        'category_id' => 13,
        'model_number' => 'MCT205-2023',
        'manufacturer' => 'Potain',
        'vehicle_number' => 'RT12QR6789',
        'owned_by' => 'rental',
        'operational_status' => 'active',
        'site_id' => 3,
        'workspace_id' => 1,
        'created_by' => 1,
        'status' => '0',
        'description' => 'Rental tower crane',
        'remarks' => 'High-rise construction',
        'capacity' => '10 tons',
        'rate_type' => 'monthly',
        'rate' => 200000.00,
        'minimum_billing_hours' => 200,
        'diesel_by_company' => true,
        'operator_by_supplier' => true,
        'number_of_operators' => 3,
        'supplier_id' => 3,
        'rental_agreement_file' => 'potain_mct205_agreement.pdf',
        'purchase_date' => null,
        'purchase_value' => null,
        'insurance_due_date' => null,
        'puc_due_date' => null,
        'fitness_due_date' => null,
        'last_service_date' => null,
        'maintenance_schedule' => null,
        'ownership_documents_file' => null,
    ],
];

echo "\nInserting " . count($machineryData) . " comprehensive machinery records...\n";

$insertCount = 0;
foreach ($machineryData as $index => $data) {
    try {
        $data['created_at'] = now();
        $data['updated_at'] = now();
        
        $id = DB::table('machineries')->insertGetId($data);
        echo "Inserted #" . ($index + 1) . ": " . $data['name'] . " (ID: " . $id . ")" . PHP_EOL;
        $insertCount++;
    } catch (Exception $e) {
        echo "Error inserting " . $data['name'] . ": " . $e->getMessage() . PHP_EOL;
    }
}

echo "\n=== SUMMARY ===\n";
echo "Total records to insert: " . count($machineryData) . PHP_EOL;
echo "Successfully inserted: " . $insertCount . PHP_EOL;
echo "Failed: " . (count($machineryData) - $insertCount) . PHP_EOL;

// Verification
$totalRecords = DB::table('machineries')->count();
echo "Total machinery records in database: " . $totalRecords . PHP_EOL;

$ownedCount = DB::table('machineries')->where('owned_by', 'owned')->count();
$rentalCount = DB::table('machineries')->where('owned_by', 'rental')->count();
echo "Owned machinery: " . $ownedCount . PHP_EOL;
echo "Rental machinery: " . $rentalCount . PHP_EOL;

if ($insertCount >= 20) {
    echo "✅ SUCCESS: Minimum 20 entries created!" . PHP_EOL;
} else {
    echo "❌ WARNING: Less than 20 entries created!" . PHP_EOL;
}
