<?php
/**
 * fix_apidog_openapi.php  –  final clean version
 *
 * Reads  uploads/scribe/openapi.yaml          (generated by scribe:generate)
 * Writes uploads/scribe/openapi_apidog_fixed.yaml
 *
 * Apidog-compatibility fixes on the generated OpenAPI 3.0.3 spec:
 *   Fix 1. Path-level parameters are never seen by Apidog.
 *             → copied into each HTTP method's own  parameters[]  array.
 *   Fix 2. requestBody without required:true is invisible to Apidog's parser.
 *             → required set to true (valid for all endpoints that have body params).
 *   Fix 3. Scribe emits `type:object, properties:{ }` for body fields whose
 *             @bodyParam annotation carries no sub-field details (e.g. approved_dates).
 *             Apidog drops those fields from the request-body UI.
 *             → post-dump YAML augmentation inserts  additionalProperties:true
 *               as a sibling to  properties  at the same indent level.
 */
require __DIR__ . '/vendor/autoload.php';
use Symfony\Component\Yaml\Yaml;

$inFile  = __DIR__ . '/uploads/scribe/openapi.yaml';
$outFile = __DIR__ . '/uploads/scribe/openapi_apidog_fixed.yaml';

if (!is_file($inFile)) {
    fwrite(STDERR, "ERROR: $inFile not found. Run `php artisan scribe:generate` first.\n");
    exit(1);
}

$y          = Yaml::parseFile($inFile, Yaml::PARSE_CONSTANT);
$stats      = ['path_params_ops' => 0, 'rb_fixed' => 0, 'empty_obj_fixed' => 0];
$httpMethods = ['get', 'post', 'put', 'patch', 'delete'];

foreach (array_keys($y['paths'] ?? []) as $pathKey) {
    $ops      = $y['paths'][$pathKey] ?? [];
    $httpKeys = array_values(array_intersect($httpMethods, array_keys($ops)));
    if (empty($httpKeys)) continue;

    // ─── Fix 1: path-level parameters → every operation ──────────────────────
    if (!empty($ops['parameters'])) {
        $pathParams = $ops['parameters'];
        foreach ($httpKeys as $m) {
            $op       =& $y['paths'][$pathKey][$m];
            $existing = $op['parameters'] ?? [];
            $keyMap   = [];
            foreach ($existing as $p) { $keyMap[($p['in'] ?? '').'.'.($p['name'] ?? '')] = true; }
            foreach ($pathParams as $pp) {
                if (!isset($keyMap[($pp['in'] ?? '').'.'.($pp['name'] ?? '')])) {
                    $existing[] = $pp;
                    $stats['path_params_ops']++;
                }
            }
            $op['parameters'] = $existing;
        }
        unset($y['paths'][$pathKey]['parameters']);
    }

    // ─── Fix 2 + 3: per-operation requestBody ────────────────────────────────
    foreach ($httpKeys as $m) {
        $op =& $y['paths'][$pathKey][$m];
        if (!isset($op['requestBody'])) continue;
        $rb =& $op['requestBody'];

        // 2a. required must be true for Apidog to render body params
        if (!isset($rb['required']) || $rb['required'] !== true) {
            $rb['required'] = true;
            $stats['rb_fixed']++;
        }

        // 2b. Walk content-type schemas to fix empty objects
        if (isset($rb['content']) && is_array($rb['content'])) {
            foreach ($rb['content'] as $ct => &$ctd) {
                if (!isset($ctd['schema'])) continue;
                walkSchema($ctd['schema'], $stats);
            }
        }
    }
}

/**
 * Mutate $node in-place: annotate any bare empty-object type with
 * additionalProperties:true so Apidog still renders it as a free-form object.
 */
function walkSchema(array &$node, array &$stats): void
{
    if (($node['type'] ?? '') === 'object') {
        if (empty($node['properties']) && !array_key_exists('additionalProperties', $node)) {
            $node['additionalProperties'] = true;
            $stats['empty_obj_fixed']++;
        }
    }
    foreach (array_keys($node) as $k) {
        if (is_array($node[$k]) && array_key_exists('type', $node[$k])) {
            walkSchema($node[$k], $stats);
        }
    }
}

// ─── Dump ────────────────────────────────────────────────────────────────────
$yml = Yaml::dump($y, 20, 2);

// ─── YAML-level safety-net ───────────────────────────────────────────────────
$yml = augmentWithSafetyNet($yml, $stats);

file_put_contents($outFile, $yml);

$total = $stats['path_params_ops'] + $stats['rb_fixed'] + $stats['empty_obj_fixed'];
echo "=== Apidog OpenAPI Fix Report ===" . PHP_EOL;
echo "  path-level params  -> op-level  : {$stats['path_params_ops']}" . PHP_EOL;
echo "  requestBody required=true      : {$stats['rb_fixed']}" . PHP_EOL;
echo "  empty-object schemas           : {$stats['empty_obj_fixed']}" . PHP_EOL;
echo "--------------------------------------------------" . PHP_EOL;
echo "  Output  : $outFile" . PHP_EOL;
echo "  Size    : " . number_format(filesize($outFile)) . " bytes" . PHP_EOL;

/**
 * Post-dump YAML augmenter.
 *
 * Pattern in the Symfony-dumped YAML string
 * (consecutive tokens on a single line, literal text):
 *
 * "{SPACES}properties: {  }\n{SPACES}{KEY}:"
 *
 * Replaced with (same indent preserved for properties and key, plus
 * additionalProperties inserted at the correct nesting level):
 *
 * "{SPACES}properties: {  }\n{SPACES}additionalProperties: true\n{SPACES}{KEY}:"
 *
 * Gets count of how many were inserted from the replacement result.
 */
function augmentWithSafetyNet(string $yml, array &$stats): string
{
    // The search needle is the Symfony-dumped empty-object literal:
    //   "properties: {  }"  followed by the trailing newline
    return augmentOnePass($yml, $stats);
}

/**
 * Single-pass augmentation.
 * Finds "properties: {  }\n" lines in the YAML string and inserts
 * "  additionalProperties: true\n" on a new line after "properties: {  }".
 * The indent for additionalProperties is computed from the YAML bytes
 * immediately BEFORE "properties"...": it is the leading-space prefix width
 * (which equals the nesting depth of the schema object) plus 10 extra spaces.
 */
function augmentOnePass(string $yml, array &$stats): string
{
    return preg_replace_callback(
        // Match: \n + INDENT + "properties: {  }" + \n
        "/(\n[ ]+)properties:\s*\{\s*\}\n/",
        function (array $m) use (&$stats): string {
            $stats['empty_obj_fixed']++;
            // $m[1] = "\n<indent spaces>"  where <indent> is the leading spaces of the line
            $indent_spaces = strlen($m[1]) - 1;     // subtract the \n byte
            // additionalProperties nests one level deeper than properties:
            // base indent + 10 extra spaces  →  matches Symfony's 2-space-per-level dump style
            $addl_indent  = str_repeat(' ', $indent_spaces + 10);
            return $m[1] . "properties: {  }\n" . $addl_indent . "additionalProperties: true\n";
        },
        $yml
    );
}
