[program:laravel-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php C:/wamp64/www/SitePilot/artisan queue:work redis --sleep=3 --tries=3 --timeout=90
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=C:/wamp64/www/SitePilot/storage/logs/queue.log
stopwaitsecs=3600

[program:laravel-queue-worker-broadcast]
process_name=%(program_name)s_%(process_num)02d
command=php C:/wamp64/www/SitePilot/artisan queue:work redis --queue=notifications --sleep=3 --tries=3 --timeout=90
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=C:/wamp64/www/SitePilot/storage/logs/queue-broadcast.log
stopwaitsecs=3600
